name: Notebooks-check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [ 3.8 ]


    steps:
      - uses: actions/checkout@v2
      - name: Run interval
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
        with:
          disable-checks: outputs,execution_count
